---
title: 'Individual Project #2'
author: "Jeodalyn Edulag"
date: "2022-12-08"
output: html_document
---

```{r, include=TRUE}
library(wordcloud)
library(plotly)
library(tm)
library(dplyr)
library(RColorBrewer)
library(ggplot2)
library(twitteR)
```

```{r, include=TRUE}
# SETUP CREDENTIALS.

CONSUMER_KEY <- "WRI54TK0xJeeuCNDOkA1Aw6TQ"
CONSUMER_SECRET <- "MJWKLwEx4I46YlWsLun5KUl3vaMJ2lsYxBIyup5bJNh3xQFYdm"
ACCESS_TOKEN <- "1595043836299878400-xDIAq9atggNBgqD1VnKxqBJQtiS9a4"
ACCESS_SECRET <- "OQ9UUEyva5I257azL7032IFLUfuOEuXY7gCGAHfoPc4fU"

setup_twitter_oauth(consumer_key = CONSUMER_KEY,
                    consumer_secret = CONSUMER_SECRET,
                    access_token = ACCESS_TOKEN,
                    access_secret = ACCESS_SECRET)

```

```{r, include=TRUE}
# EXTRACTING TWEETS.
tp_tweets <- searchTwitter("Indonesia", n=10000, lang="en", 
                           since="2022-11-28", until="2022-12-4", 
                           retryOnRateLimit = 120)
tp_tweets
```


```{r, include=TRUE}
# CONVERTING LIST DATA TO DATA FRAME.
tp_tweetsDF <- twListToDF(tp_tweets)
```


```{r, include=TRUE}
# SAVE DATA FRAME FILE.
save(tp_tweetsDF,file = "indonesiaTweetsDF.Rdata")
```

```{r, include=TRUE}
# LOAD DATA FRAME FILE.
load(file = "indonesiaTweetsDF.Rdata")
```

```{r, include=TRUE}
# CHECKING FOR MISSING VALUES IN A DATA FRAME.
sd <- sapply(tp_tweetsDF, function(x) sum(is.na(x)))
sd
```

```{r, include=TRUE}
#Tweets
# SUBSETTING USING THE dplyr() PACKAGE.
twts <- tp_tweetsDF %>%
  select(screenName,text,created, isRetweet) %>% filter(isRetweet == FALSE)
twts
```

```{r, include=TRUE}
# GROUPING THE DATA CREATED. 
twts %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))

cd <- twts %>%  mutate(Created_At_Round = created %>% round(units = 'hours') %>% as.POSIXct())
cd

minj <- twts %>% pull(created) %>% min()
minj
maxj <- twts %>% pull(created) %>% max()
maxj
```

```{r, include=TRUE}
# Plot on tweets by time using the library(plotly) and ggplot().
plot_d <- ggplot(cd, aes(x = Created_At_Round)) +
  geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") +
  xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "midnightblue", high = "aquamarine4")

plot_d %>% ggplotly()
```

#==============

```{r, include=TRUE}
#Retweets

s_tweets <- tp_tweetsDF %>%
  select(screenName,text,created, isRetweet) %>% filter(isRetweet == TRUE)
s_tweets

s_tweets %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))

c2 <- s_tweets %>%  mutate(Created_At_Round = created %>% round(units = 'hours') %>% as.POSIXct())
c2

minj <- s_tweets %>% pull(created) %>% min()
minj 
maxj <- s_tweets %>% pull(created) %>% max()
maxj
```

```{r, include=TRUE}
# Plot on tweets by time using the library(plotly) and ggplot().
plot_d <- ggplot(c2, aes(x = Created_At_Round)) +
  geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") +
  xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "pink", high = "cyan")

plot_d %>% ggplotly()
```