---
title: "Individual_Project_Edulag#1"
author: "Jeodalyn Edulag"
date: "2022-12-06"
output: html_document
---

```{r, include=TRUE}
library(wordcloud)
library(plotly)
library(tm)
library(dplyr)
library(RColorBrewer)
library(ggplot2)
library(twitteR)
library(slam)
library(magrittr)
library(tidytext)
library(rtweet)
library(corpus)

```

```{r, include=TRUE}
# SETUP CREDENTIALS.

CONSUMER_KEY <- "WRI54TK0xJeeuCNDOkA1Aw6TQ"
CONSUMER_SECRET <- "MJWKLwEx4I46YlWsLun5KUl3vaMJ2lsYxBIyup5bJNh3xQFYdm"
ACCESS_TOKEN <- "1595043836299878400-xDIAq9atggNBgqD1VnKxqBJQtiS9a4"
ACCESS_SECRET <- "OQ9UUEyva5I257azL7032IFLUfuOEuXY7gCGAHfoPc4fU"

setup_twitter_oauth(consumer_key = CONSUMER_KEY,
                    consumer_secret = CONSUMER_SECRET,
                    access_token = ACCESS_TOKEN,
                    access_secret = ACCESS_SECRET)

```

```{r, include=TRUE}
# EXTRACTING TWEETS.
trendTweets <- searchTwitter("Indonesia -filter:retweets", n=10000, lang="en", 
                             since="2022-11-28", until="2022-12-4", 
                             retryOnRateLimit = 120)
trendTweets
```

```{r, include=TRUE}
# CONVERTING LIST DATA TO DATA FRAME.
t_TweetsDF1 <- twListToDF(trendTweets)
class(t_TweetsDF1)
names(t_TweetsDF1)
View(t_TweetsDF1)
head(t_TweetsDF1)[1:5]
head(t_TweetsDF1$text)[1:5]
```

```{r, include=TRUE}
# SAVE DATA FRAME FILE.
save(t_TweetsDF1,file = "trendingTweetsDF.Rdata")
```

```{r, include=TRUE}
# LOAD DATA FRAME FILE.
load(file = "trendingTweetsDF.Rdata")
```

```{r, include=TRUE}
# SAVING FILE AS RDATA.
save(t_TweetsDF1, file = "tweetsDF2.Rdata")
```

```{r, include=TRUE}
# CHECKING FOR MISSING VALUES IN A DATA FRAME.
s <- sapply(t_TweetsDF1, function(x) sum(is.na(x)))
s
```

```{r, include=TRUE}
# SUBSETTING USING THE dplyr() PACKAGE.
t_TweetsDF2 <- t_TweetsDF1 %>%
  select(screenName,text,created,statusSource)
t_TweetsDF2
```

```{r, include=TRUE}
# GROUPING THE DATA CREATED. 
t_TweetsDF2 %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))

mutatej <- t_TweetsDF2 %>%  mutate(Created_At_Round = created %>% round(units = 'hours') %>% as.POSIXct())
mutatej

t_TweetsDF2 %>% pull(created) %>% min() 
t_TweetsDF2 %>% pull(created) %>% max()
```

```{r, include=TRUE}
# Plot on tweets by time using the library(plotly) and ggplot().
plot <- mutatej %>% 
  dplyr::count(Created_At_Round) %>% 
  ggplot(mapping = aes(x = Created_At_Round, y = n)) +
  theme_light() +
  geom_line() +
  xlab(label = 'Date') +
  ylab(label = NULL) +
  ggtitle(label = 'Number of Tweets per Hour')

plot %>% ggplotly()
```

# ==============================================

```{r, include=TRUE}
ggplot(data = t_TweetsDF2, aes(x = created)) +
  geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") +
  xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "pink", high = "cyan")
```

```{r, include=TRUE}
# PLOTTING STATUS SOURCE.
encodeSource <- function(x) {
  if(grepl(">Twitter for iPhone</a>", x)){
    "iphone"
  }else if(grepl(">Twitter for iPad</a>", x)){
    "ipad"
  }else if(grepl(">Twitter for Android</a>", x)){
    "android"
  } else if(grepl(">Twitter Web Client</a>", x)){
    "Web"
  } else if(grepl(">Twitter for Windows Phone</a>", x)){
    "windows phone"
  }else if(grepl(">dlvr.it</a>", x)){
    "dlvr.it"
  }else if(grepl(">IFTTT</a>", x)){
    "ifttt"
  }else if(grepl(">Facebook</a>", x)){  
    "facebook"
  }else {
    "others"
  }
}


t_TweetsDF2$tweetSource = sapply(t_TweetsDF2$statusSource, 
                                 encodeSource)

tweet_appSource1 <- t_TweetsDF2 %>% 
  select(tweetSource) %>%
  group_by(tweetSource) %>%
  summarize(count=n()) %>%
  arrange(desc(count))

ggplot(t_TweetsDF2[t_TweetsDF2$tweetSource != 'others',], aes(tweetSource, fill = tweetSource)) +
  geom_bar() +
  theme(legend.position="none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Number of tweets") +
  ggtitle("Tweets by Source")
```

```{r, include=TRUE}
# ACCOUNTS WHICH TWEET ABOUT INDONESIA.
tweet_appScreen1 <- t_TweetsDF2 %>%
  select(screenName) %>%
  group_by(screenName) %>%
  summarize(count=n()) %>%
  arrange(desc(count)) 
```

```{r, include=TRUE}
#convert to Corpus
namesCorpus <- Corpus(VectorSource(t_TweetsDF2$screenName))  #using ScreenName
class(t_TweetsDF2$screenName)

c_data <- class(VectorSource(t_TweetsDF2$screenName))
c_data

str(namesCorpus)

class(namesCorpus)

numb <- namesCorpus
numb
```

```{r, include=TRUE}
# WORDCLOUD FOR SCREEN_NAMES.
palt7 <- brewer.pal(8, "Dark2")
palt2 <- palt7[-(1:4)]
set.seed(123)

par(mar = c(0,0,0,0), mfrow = c(1,1))

wordcloud(words = namesCorpus, scale=c(3,0.5),
          max.words=10000,
          random.order=FALSE,
          rot.per=0.5,
          use.r.layout=TRUE,
          colors=palt7)
```
